counter_uas_yolov8p2_infer_node:
  ros__parameters:
    CUI:
      frameRate: 30
      saveResImgDt: 1.0
      engineFile: "/yolo_trt_engine/yolov8/dronecop9-2.engine"
      useDebugMode: true

      inferPlayMode:
        mode: 222 # 111: image, 222: video, 333: topic
        enableSaveRes: false
        enableSaveImgVidOnly: false
        saveFileName: "infer_res_"
        topic:
          imgDstTopicName: "/infered_image_dst"
          compDstTopicName: "/infered_comp_dst" 
          sourceTopicName: "/camera/image_raw"
          saveFrameSrcPath: "/yolo_trt_engine/yolov8/infer_topic/frame_src/"
          saveFrameDstPath: "/yolo_trt_engine/yolov8/infer_topic/frame_dst/img/"
          saveLabelDstPath: "/yolo_trt_engine/yolov8/infer_topic/frame_dst/yolo_label/" 
        
        video:
          folderPath: "/yolo_trt_engine/yolov8/infer_vids/src/kari_antidrone/"
          fileName: "test.mp4" #"test_north_uav_trimmed.mp4"
          imgRawTopicName: "/video/image_raw"
          saveImgSrcPath: "/yolo_trt_engine/yolov8/infer_vids/frame_src/"
          saveImgDstPath: "/yolo_trt_engine/yolov8/infer_vids/frame_dst/img/"
          saveLabelDstPath: "/yolo_trt_engine/yolov8/infer_vids/frame_dst/yolo_label/"
          saveVidDstPath: "/yolo_trt_engine/yolov8/infer_vids/infer_video_result_"
        
        image:
          srcFolderPath: "/yolo_trt_engine/yolov8/infer_imgs/src/kari_antidrone"
          dstFolderPath: "/yolo_trt_engine/yolov8/infer_imgs/dst/img/"
          labelFolderPath: "/yolo_trt_engine/yolov8/infer_imgs/dst/yolo_label/"
      
      threshold:
        nmsThVal: 0.5
        confVal: 0.5
    